### ISSUE TITLE
 re-implementation of these regularization loss layers in pytorch

### ISSUE THREAD

**Issue by wyk0517** [meng-tang/rloss#1]
hi，are you finish the  re-implementation of these regularization loss layers in pytorch？ can you share me a counterpart code of 《Normalized Cut Loss for Weakly-supervised CNN Segmentation》.

**Comment by meng-tang** [comment]
I'm working on this and will release pytorch version for various losses. Stay tuned. Thanks for your interest.

**Comment by wyk0517** [comment]
> I'm working on this and will release pytorch version for various losses. Stay tuned. Thanks for your interest.

Thanks for your reply, you are very nice! 
I have some questions about 《Normalized Cut Loss for Weakly-supervised CNN Segmentation》:

The paper show some pictures with scribbles, I wanna know if there are several same kind objects, I only want to segment one of them and ignore others in inference, how about the performance ? The model can work well? emmm, for example, there are three people in a picture(maybe they are very close), I only wanna to segment one person, and the rest two people need to be viewed as background. In this situation the model in paper will work?

My English is poor, I hope I describe it clearly and you don't mind this.

**Comment by wyk0517** [comment]
> I'm working on this and will release pytorch version for various losses. Stay tuned. Thanks for your interest.

Hi，when you finish the pytorch version for various losses, will you update this project? or make a new project in github? Can you make a announcement in this project? I am reading your a series of weakly-supervised papers, it's excellent! I am a newbie in this, and I wanna read paper and code to be practised .
So I'm expecting your code in pytorch~

**Comment by stefat77** [comment]
> > I'm working on this and will release pytorch version for various losses. Stay tuned. Thanks for your interest.
> 
> Thanks for your reply, you are very nice!
> I have some questions about 《Normalized Cut Loss for Weakly-supervised CNN Segmentation》:
> 
> The paper show some pictures with scribbles, I wanna know if there are several same kind objects, I only want to segment one of them and ignore others in inference, how about the performance ? The model can work well? emmm, for example, there are three people in a picture(maybe they are very close), I only wanna to segment one person, and the rest two people need to be viewed as background. In this situation the model in paper will work?
> 
> My English is poor, I hope I describe it clearly and you don't mind this.

If you scribble all the people with the background line and the person that you want to segment with the foreground line it should still work

**Comment by wyk0517** [comment]
> > > I'm working on this and will release pytorch version for various losses. Stay tuned. Thanks for your interest.
> > 
> > 
> > Thanks for your reply, you are very nice!
> > I have some questions about 《Normalized Cut Loss for Weakly-supervised CNN Segmentation》:
> > The paper show some pictures with scribbles, I wanna know if there are several same kind objects, I only want to segment one of them and ignore others in inference, how about the performance ? The model can work well? emmm, for example, there are three people in a picture(maybe they are very close), I only wanna to segment one person, and the rest two people need to be viewed as background. In this situation the model in paper will work?
> > My English is poor, I hope I describe it clearly and you don't mind this.
> 
> If you scribble all the people with the background line and the person that you want to segment with the foreground line it should still work

ok， Thanks! Now, I just look forward to the re-implement~

**Comment by Thebluebluesky** [comment]
> I'm working on this and will release pytorch version for various losses. Stay tuned. Thanks for your interest.

Hi, this is very nice that you are going to release a pytorch vision for your work. 
Because I am a little confused when I read the paper, and I want to see more details through a code.
Can I get to know when will you release the pytorch code? 
Thanks for your nice.

**Comment by meng-tang** [comment]
Sorry for late reply. Let me know any issue with the pytorch version.
https://github.com/meng-tang/rloss/tree/master/pytorch
