### ISSUE TITLE
annotation label

### ISSUE THREAD

**Issue by teeinn** [meng-tang/rloss#16]
Hi, I am trying to implement training with pascal voc dataset in pytorch. 
While searching for the code that imports scribble annotation xml file, I realized 
it only imports images from JPEG folder (original image) and pascal 2012 scribble folder (scribble images, all scribble is black color).
I might be misunderstanding your paper or code,, but how come training is working not knowing class label for each of lines all colored black? 
Waiting for your quick response!

**Comment by meng-tang** [comment]
The scribbles look black, but the pixel values are actually 0-20 which correspond to class labels

**Comment by teeinn** [comment]
oh!!!!!!!!!! I see!!! Thank you so much! it really does have different values! 
so then, are these images (pascal 2012 scribble dir) created based on xml annotation file? 
I mean, I know this dataset is from scribblesub (they mentioned amazon mechanical turk,) but do you have any transition code for the process?

**Comment by meng-tang** [comment]
yes, you can recreate from https://github.com/meng-tang/rloss/blob/master/data/pascal_scribble/convertscribbles.m (credit to http://www.jifengdai.org/downloads/scribble_sup )

**Comment by teeinn** [comment]
Thank you for your quick response!!
