### ISSUE TITLE
Dear， be quickly！

### ISSUE THREAD

**Issue by wyk0517** [meng-tang/rloss#4]
I am waiting your pytorch code～ it's so hard！ quickly please～

**Comment by stefat77** [comment]
> I am waiting your pytorch code～ it's so hard！ quickly please～

Man, be patient! :D

**Comment by brisyramshere** [comment]
i am waitung pytorch version too!hahaha





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by meng-tang** [comment]
Sorry for late reply. Please try the pytorch version at:
https://github.com/meng-tang/rloss/tree/master/pytorch
